---
branches:
  only:
    - develop
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk:
  - openjdk11
language: java
notifications:
  email:
    recipients:
      - support@grooteogi.net
script:
  - "cd ./api"
  - "./gradlew clean build"