branches:
  only:
    - develop
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk:
  - openjdk11
language: java
notifications:
  email:
    recipients:
      - support@grooteogi.net
script:
  - "cd ./api"
  - "./gradlew clean build"
before_deploy:
  - zip -r Grooteogi *
  - mkdir -p deploy
  - mv Grooteogi.zip deploy/Grooteogi.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-grooteogi
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true
