version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/grooteogi/zip
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: /etc/profile.d/codedeploy.sh
      timeout: 10
      runas: ubuntu
    - location: deploy.sh
      timeout: 60
      runas: ubuntu