version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pw
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    networks:
      - db_network
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - db_network
    restart: always
  api:
    container_name: spring-boot
    ports:
      - "8080:8080"
    build: ./api
    env_file:
      - "./api/config/dev.env"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test_pw
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - db_network
    restart: always
networks:
  db_network:
    driver: bridge
