spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: grtg.1900@gmail.com
    password: grooteogi19*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true