spring:
  datasource:
    url: jdbc:mysql://localhost:3305/test_db
    username: test
    password: test_pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6378
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: region
    s3:
      bucket: GRTG
