spring:
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: ${JWT_KEY}
  session:
    timeout: 300
    store-type : redis
    redis:
      namespace: spring:session
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: $(AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: GRTG
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          client-id: ${GOOGLE_CLIENT_ID}
#          client-secret: ${GOOGLE_CLIENT_SECRET_ID}
#          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#custom:
#  oauth2:
#    kakao:
#      client-id: ${KAKAO_CLIENT_ID}
#      client-secret: ${KAKAO_CLIENT_SECRET_ID}