spring:
  datasource:
    url: jdbc:mysql://localhost:3305/test_db
    username: test
    password: test_pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: test_mail
    password: test_pw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6378
  jwt:
    secret: grooteogi
  session:
    timeout: 300
    store-type : redis
    redis:
      namespace: spring:session
