spring:
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: ${JWT_KEY}
  session:
    timeout: 300
    store-type : redis
    redis:
      namespace: spring:session