name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    env:
      working-directory: ./api
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache Gradle cache files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: Run checkstyleMain
        run: ./gradlew -q checkstyleMain
        working-directory: ${{ env.working-directory }}

      - name: Run checkstyleTest
        run: ./gradlew -q checkstyleTest
        working-directory: ${{ env.working-directory }}
